spring.application.name=springboot-user-management-api

spring.datasource.url=jdbc:postgresql://localhost:5433/usermanagement
spring.datasource.username=postgres
spring.datasource.password=nk@4ever

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


logging.level.root=INFO
logging.level.com.nk.usermanagement=DEBUG
//logging.file.name=app.log